version: "3"

services:

  lighttpd:
    image: bx-installer_lighttpd
    container_name: "${COMPOSE_PROJECT_NAME}_lighttpd"
    tty: true
    ports:
      - "${PUBLIC_PORT}:80"
    volumes:
      - "${LIGHTTPD_VOLUMES_PREFIX}/etc/lighttpd:/etc/lighttpd"
      - 'bitrix-core:/opt/www'
    depends_on:
        - bitrix

  php:
    image: bx-installer_php
    container_name: "${COMPOSE_PROJECT_NAME}_php"
    entrypoint: [ '/docker-php-entrypoint', 'php-fpm' ]
    network_mode: service:lighttpd
    volumes:
      - "${PHP_VOLUMES_PREFIX}/usr/local/etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf"
      - "${PHP_VOLUMES_PREFIX}/usr/local/etc/php/php.ini:/usr/local/etc/php/php.ini"
      - "${PHP_VOLUMES_PREFIX}/docker-php-entrypoint:/docker-php-entrypoint"
      - 'bitrix-core:/opt/www'
      # - '${PHP_VOLUMES_PREFIX}/.settings.php:/opt/www/bitrix/.settings.php'
    depends_on:
        - lighttpd
        - bitrix

  mysql:
    image: bx-installer_mysql
    container_name: "${COMPOSE_PROJECT_NAME}_mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DB_NAME
      # MYSQL_USER: $MYSQL_DB_USER
      # MYSQL_PASSWORD: $MYSQL_DB_PASSWORD
    network_mode: service:lighttpd
    volumes:
      - 'bitrix-db:/var/lib/mysql'
    depends_on:
        - lighttpd
        - bitrix-db

  bitrix:
    image: bx-origin_bitrix:latest
    container_name: "${COMPOSE_PROJECT_NAME}_bitrix"
    volumes:
      - 'bitrix-core:/tmp/bitrix-core'

  bitrix-db:
    image: bx-origin_bitrix-db:latest
    container_name: "${COMPOSE_PROJECT_NAME}_bitrix-db"
    volumes:
      # - '${POD_ROOT}/services/bitrix-db/volumes/docker-entrypoint.sh:/docker-entrypoint.sh'
    volumes:
      - 'bitrix-db:/tmp/mysql'


volumes:
  bitrix-core:
  bitrix-db:
